### ISSUE TITLE
Cut new release to fix SSL support

### ISSUE THREAD

**Issue by MattSurabian** [rockymadden/gap#9]
The latest tagged release `v.0.5.6` has coffeescript typo that causes gap to not support SSL. The addition of parens in [core.coffee](https://github.com/rockymadden/gap/blob/master/src/main/coffeescript/core.coffee#L12) has fixed this in master, but there's no release yet :cry: 

Any idea when the next release will be?

**Comment by MattSurabian** [comment]
Any status on this @rockymadden?

**Comment by rockymadden** [comment]
Ah jeez, let me do this now. My apologies, I don't believe I have alerts on for this repo until recently. I'll ping you in this thread when I am done.

**Comment by rockymadden** [comment]
Should be all set @MattSurabian with v0.7.0.
